export const config = {
  redisUrl: process.env.REDIS_URL ?? "redis://localhost:6379",
  databaseUrl: process.env.DATABASE_URL ?? "postgresql://rag:rag@localhost:5434/rag",
  s3: {
    endpoint: process.env.S3_ENDPOINT ?? "http://localhost:9000",
    accessKey: process.env.S3_ACCESS_KEY ?? "minioadmin",
    secretKey: process.env.S3_SECRET_KEY ?? "minioadmin",
    bucket: process.env.S3_BUCKET ?? "rag-documents",
    region: process.env.S3_REGION ?? "us-east-1",
    forcePathStyle: process.env.S3_FORCE_PATH_STYLE !== "false",
  },
  drive: {
    trashRetentionDays: Number(process.env.TRASH_RETENTION_DAYS ?? 30),
  },
  purgeIntervalMs: Number(process.env.PURGE_INTERVAL_MS ?? 60 * 60 * 1000),
  ocrConcurrency: Number(process.env.OCR_CONCURRENCY ?? 2),
  maxPagesPerOcrJob: Number(process.env.MAX_PAGES_PER_OCR_JOB ?? 50),
  tesseractLang: process.env.TESSERACT_LANG ?? 'eng',
  playwrightTimeoutMs: 15000,
  webUrlMaxBytes: 10 * 1024 * 1024,
  rateLimitWindowMs: Number(process.env.RATE_LIMIT_WINDOW_MS ?? 60_000),
  openAiApiKey: process.env.OPENAI_API_KEY ?? '',
  embeddingModel: process.env.EMBEDDING_MODEL ?? 'text-embedding-3-small',
  embeddingBatchSize: Number(process.env.EMBEDDING_BATCH_SIZE ?? 100),
} as const;
